### ISSUE TITLE
Add support for makeglossaries

### ISSUE THREAD

**Issue by mbellgb** [thomasjo/atom-latex#179]
It would be great if there was a setting to allow the user to add extra commands during compilation, for instance the `makeglossaries` command.

**Comment by thomasjo** [comment]
I fully agree. I've been contemplating the best way of implementing this for a little while now. Will try to find some time to document it either here, or in a placeholder PR.

**Comment by thbtmntgn** [comment]
+1 !
Do you have some news @thomasjo ?

**Comment by thomasjo** [comment]
@thbtmntgn Sadly this was put on The Backburner™, but now that I've implemented Knitr support, I'm feeling pretty confident about implementing some manner of pipeline system. Such a system might involve invoking `makeglossaries`, `makeindex`, Knitr, etc.

The biggest issue is deciding on how to let the user control/specify the pipeline. The simplest approach might be something akin to arara which simply uses comments. I want to begin by implementing the simplest possible solution though, so a full-blown pipeline concept might be too complex 🔮

**Comment by sinh15** [comment]
Hi there,

Sorry to disturb you guys, I'm new to latex and quite super lost. 

I'm trying to build the glosseries through atom and although the functionality that you are discussing is still not in place, any idea on how could I approach the display of acronyms and glossaries in the meanwhile? Even if it's through console. Any input would be welcome!

Actually, running the command `\printglossaries{}` is displaying the Acronyms, but not the Glossary.

Sorry for disturbing in here.

**Comment by yitzchak** [comment]
Support for `makeglossaries` will be in the next version. This is done by using `latexmk` custom rules. Also, support for Asymptote, MetaPost, `nomencl`, `index` and SageTeX is being added using the same mechanism.

Cheers!
